#config/local.yaml

env: "local"  #окружение - local, dev, или prod
storage_path: "./storage/storage.db"
app_secret: "test-secret"
http_server: #конфигурация нашего http-сервера
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 30s
  user: "my_user"
  password: "my_pass"
clients: #конфигурация клиента gRPC
  sso:
    address: "localhost:44044"
    timeout: 10s
    retriesCount: 3